USE almacen;

DELIMITER $
-- ---------------------------------------------------------------------------CONCURRENCIA------------------------------------------------------
DROP PROCEDURE IF EXISTS USUARIO1;$

CREATE PROCEDURE USUARIO1()
BEGIN
	CALL INSERTARUSUARIO('felipe','contrasena','felipe@hotmail.com');
	CALL INSERTARUSUARIO('fernando','123','fer@hotmail.com');
	CALL INSERTARUSUARIO('carmen','carmen123','carmen@hotmail.com');
	
	SELECT COMPROBARLOGIN('felipe','contrasena');
		
		CALL REGISTROCLIENTE('8392','gustavo adolfo','3ra ave 4-39 zona 21',62871323,'100');
		CALL REGISTROCLIENTE('8270','perez blanco','4ta calle 7-384 zona 2',83927839,'100');
		CALL REGISTROCLIENTE('3142','pluto barracus','4ta ave 2-32 zona 1',82938263,'100');
		
		CALL REGISTROPROVEEDOR('7141','Gelatix s.a','3ra ave 7-23 zona 4',94827362,'gelatix@gmail.com','100');
		CALL REGISTROPROVEEDOR('8230','Comanfer s.a','5ta calle 2-38 zona 15',83927382,'comanfer@hotmail.com','100');
		CALL REGISTROPROVEEDOR('3333','yulbri s.a','6ta ave 8-22 zona 14',22739283,'yukbr@yahoo.com','100');
	
		CALL REGISTROPRODUCTO(839,'Bolsa','bolsas para guardar cosas para dama','C:/imagen1.jpg','100');
		CALL REGISTROPRODUCTO(840,'Pantalon','Pantalones marca jensi para dama','C:/imagen2.jpg','100');
		CALL REGISTROPRODUCTO(841,'Cincho','cincho unisex','C:/imagen3.jpg','100');
		CALL REGISTROPRODUCTO(842,'Yogurt','yogurt lala para el consumo','C:/imagen5.jpg','100');
		CALL REGISTROPRODUCTO(843,'Escoba','escoba para limpieza','C:/imagen6.jpg','100');
		CALL REGISTROPRODUCTO(844,'Pala','pala para limpieza','C:/imagen7.jpg','100');
		CALL REGISTROPRODUCTO(845,'Leche','leche entera en polvo','C:/imagen8.jpg','100');
		
		CALL REGISTROEMPLEADO(122,'Mari Lopez','5ta calle d 3-05 zona 2 BDM',55140101,'100');
		CALL REGISTROEMPLEADO(321,'Marubeni De Leon','5ta calle d 3-32 zona 2 BDM',54829302,'100');
	
		CALL REGISTROMERMA(1,7,'Vencimiento del producto de yogurt',57.25,'2015/06/06',842);
		CALL REGISTROMERMA(2,2,'Vencimiento del producto de leche',23.15,'2015/06/07',845);
		CALL REGISTROMERMA(3,3,'Vencimiento del producto de leche',30.2,'2015/06/10',845);
	CALL ELIMINARUSUARIO('felipe');
END;$

DROP PROCEDURE IF EXISTS USUARIO2;$

CREATE PROCEDURE USUARIO2()
BEGIN	
	DECLARE ORDEN INT DEFAULT 1;
	DECLARE INICIAL INT;
	DECLARE IDFACTURA INT;
	DECLARE ITERACION INT DEFAULT 0;
	DECLARE PRECIO REAL DEFAULT 3.32;
	DECLARE PRODUCTO INT DEFAULT 839;
	
	
	SELECT COMPROBARLOGIN('carmen','federica');
	SELECT COMPROBARLOGIN('carmen','carmen123');
	
	SET ITERACION = 0;
	WHILE ITERACION < 5 DO
		SET IDFACTURA = RAND() * 1500;
		CALL REGISTROCOMPRA(IDFACTURA,FROM_UNIXTIME(RAND() * 2147483647),'COMPRA A PROVEEDOR YULBRI','3333');
			SET INICIAL = RAND() * 1500;
			SET ORDEN = INICIAL;
			WHILE ORDEN <INICIAL+15 DO
				SET PRODUCTO = PRODUCTO + RAND()*7;
				SET PRECIO = ROUND(PRECIO + 2.3 * (RAND()*7),2);
				SET ORDEN = ORDEN+1;
				CALL REGISTRODETALLECOMPRA(ORDEN,PRECIO,RAND()*22,IDFACTURA,PRODUCTO);
			END WHILE;
		SET ITERACION = ITERACION + 1;
	END WHILE;
	
	CALL REGISTROCLIENTE('8270','perez blanco','4ta calle 7-384 zona 2',72839272,'010');
	CALL REGISTROCLIENTE('3142','pluto barracus','4ta ave 2-32 zona 4',82938263,'010');
		
	SET ITERACION = 0;
	WHILE ITERACION < 5 DO
		SET IDFACTURA = RAND() * 2000;
		CALL REGISTROCOMPRA(IDFACTURA,FROM_UNIXTIME(RAND() * 2147483647),'COMPRA A PROVEEDOR GELATIX','7141');
			SET INICIAL = RAND() * 2000;
			SET ORDEN = INICIAL;
			WHILE ORDEN <INICIAL+10 DO
				SET PRODUCTO = PRODUCTO + RAND()*7;
				SET PRECIO = ROUND(PRECIO + 34.3 * (RAND()*7),2);
				SET ORDEN = ORDEN+1;
				CALL REGISTRODETALLECOMPRA(ORDEN,PRECIO,RAND()*30,IDFACTURA,PRODUCTO);
			END WHILE;
		SET ITERACION = ITERACION + 1;
	END WHILE;
	
	SET ITERACION = 0;
	WHILE ITERACION < 5 DO
		SET IDFACTURA = RAND() * 2500;
		CALL REGISTROVENTA(IDFACTURA,FROM_UNIXTIME(RAND() * 2147483647),'VENTA A CLIENTE',321,'8270');
			SET INICIAL = RAND() * 2500;
			SET ORDEN = INICIAL;
			WHILE ORDEN <INICIAL+20 DO
				SET PRODUCTO = PRODUCTO + RAND()*7;
				SET PRECIO = ROUND(PRECIO + 73.2 * (RAND()*7),2);
				SET ORDEN = ORDEN+1;
				CALL REGISTRODETALLEVENTA(ORDEN,PRECIO,RAND()*44,IDFACTURA,PRODUCTO);
			END WHILE;
		SET ITERACION = ITERACION + 1;
	END WHILE;
	
	SET ITERACION = 0;
	WHILE ITERACION < 5 DO
		SET IDFACTURA = RAND() * 3500;
		CALL REGISTROVENTA(IDFACTURA,FROM_UNIXTIME(RAND() * 2147483647),'VENTA A CLIENTE',122,'3142');
			SET INICIAL = RAND() * 3500;
			SET ORDEN = INICIAL;
			WHILE ORDEN <INICIAL+23 DO
				SET PRODUCTO = PRODUCTO + RAND()*7;
				SET PRECIO = ROUND(PRECIO + 73.2 * (RAND()*7),2);
				SET ORDEN = ORDEN+1;
				CALL REGISTRODETALLEVENTA(ORDEN,PRECIO,RAND()*50,IDFACTURA,PRODUCTO);
			END WHILE;
		SET ITERACION = ITERACION + 1;
	END WHILE;
END;$


DROP PROCEDURE IF EXISTS USUARIO3;$

CREATE PROCEDURE USUARIO3()
BEGIN	
	DECLARE ORDEN INT DEFAULT 1;
	DECLARE INICIAL INT;
	DECLARE IDFACTURA INT;
	DECLARE ITERACION INT DEFAULT 0;
	DECLARE PRECIO REAL DEFAULT 3.32;
	DECLARE PRODUCTO INT DEFAULT 839;
	
	
	SELECT COMPROBARLOGIN('fernando','123');
		
	SET ITERACION = 0;
	WHILE ITERACION < 5 DO
		SET IDFACTURA = RAND() * 4000;
		CALL REGISTROVENTA(IDFACTURA,FROM_UNIXTIME(RAND() * 2147483647),'VENTA A CLIENTE',122,'8392');
			SET INICIAL = RAND() * 4000;
			SET ORDEN = INICIAL;
			WHILE ORDEN <INICIAL+25 DO
				SET PRODUCTO = PRODUCTO + RAND()*7;
				SET PRECIO = ROUND(PRECIO + 49.5 * (RAND()*7),2);
				SET ORDEN = ORDEN+1;
				CALL REGISTRODETALLEVENTA(ORDEN,PRECIO,RAND()*14,IDFACTURA,PRODUCTO);
			END WHILE;
		SET ITERACION = ITERACION + 1;
	END WHILE;
	
	CALL REGISTROTIPOGASTO(738,'GASTOS DE ELECTRICIDAD','SERVICIO DE LUZ ELECTRICA PARA EL LOCAL, ALUMBRADO PUBLICO');
	CALL REGISTROTIPOGASTO(739,'GASTOS DE INMUEBLES','TIPO DE GASTO PARA EL ARRENDAMIENTO DE LOCALES'); 
	CALL REGISTROTIPOGASTO(740,'GASTOS DE AGUA','TIPO DE GASTO PARA AGUA');
	
	SET ITERACION = 0;
	WHILE ITERACION < 5 DO
		SET IDFACTURA = RAND() * 4000;
		CALL REGISTROVENTA(IDFACTURA,FROM_UNIXTIME(RAND() * 2147483647),'VENTA A CLIENTE',122,'3142');
			SET INICIAL = RAND() * 4000;
			SET ORDEN = INICIAL;
			WHILE ORDEN <INICIAL+10 DO
				SET PRODUCTO = PRODUCTO + RAND()*7;
				SET PRECIO = ROUND(PRECIO + 27.32 * (RAND()*7),2);
				SET ORDEN = ORDEN+1;
				CALL REGISTRODETALLEVENTA(ORDEN,PRECIO,RAND()*30,IDFACTURA,PRODUCTO);
			END WHILE;
		SET ITERACION = ITERACION + 1;
	END WHILE;
	
	SET ITERACION = 0;
	PRIMERFOR: LOOP     
		 SET ITERACION = ITERACION + 1;
         CALL REGISTROGASTO(ITERACION,FROM_UNIXTIME(RAND() * 2147483647),ROUND(RAND()*343.50,2),738+RAND()*2,321);
         IF ITERACION=6 THEN
            LEAVE PRIMERFOR;
         END IF;
	END LOOP PRIMERFOR;
	
	SEGUNDOFOR: LOOP     
		 SET ITERACION = ITERACION + 1;
         CALL REGISTROGASTO(ITERACION,FROM_UNIXTIME(RAND() * 2147483647),ROUND(RAND()*323.30,2),738+RAND()*2,122);
         IF ITERACION=15 THEN
            LEAVE SEGUNDOFOR;
         END IF;
	END LOOP SEGUNDOFOR;
   

END;$


DROP PROCEDURE IF EXISTS USUARIO4;$

CREATE PROCEDURE USUARIO4()
BEGIN	
	CALL LLAMADAVISTA(1);
	CALL LLAMADAVISTA(2);
	CALL LLAMADAVISTA(3);
	CALL LLAMADAVISTA(4);
END$
-- INSERTARUSUARIO(IN NICK VARCHAR(50),IN PASS VARCHAR(20),IN EMAILR VARCHAR(60))
-- ELIMINARUSUARIO(IN NICK VARCHAR(50))
-- REGISTROCLIENTE(IN NITR INT, IN NOMBRER VARCHAR(60), IN DIRECCIONR VARCHAR(100),IN TELEFONOR INT,IN ACCIONR VARCHAR(3))
-- REGISTROPROVEEDOR(IN NITPROVEEDORR INT, IN NOMBRER VARCHAR(60), IN DIRECCIONR VARCHAR(100),IN TELEFONOR INT,IN EMAILR VARCHAR(60),IN ACCIONR VARCHAR(3))
-- REGISTROEMPLEADO(IN DPIR INT, IN NOMBRER VARCHAR(60), IN DIRECCIONR VARCHAR(100),IN TELEFONOR INT,IN ACCIONR VARCHAR(3))
-- REGISTROPRODUCTO(IN IDPRODUCTOR INT, IN NOMBRER VARCHAR(60), IN DESCRIPCIONR TEXT(200),IN IMAGENR TEXT(100),IN ACCIONR VARCHAR(3))
-- REGISTROCOMPRA(IN IDFACTURAR INT, IN FECHAR DATE, IN DESCRIPCIONR TEXT(200),IN NITPROVEEDORR INT)
-- REGISTRODETALLECOMPRA(IN IDDETALLECOMPRAR INT, IN PRECIOR REAL, IN CANTIDADR INT,IN IDFACTURACOMPRAR INT,IN IDPRODUCTOR INT )
-- REGISTROVENTA(IN IDFACTURAR INT, IN FECHAR DATETIME, IN DESCRIPCIONR TEXT(200), IN DPIVENDEDORR INT,IN NITCLIENTER INT)
-- REGISTRODETALLEVENTA(IN IDDETALLEVENTAR INT, IN PRECIOR REAL, IN CANTIDADR INT,IN IDFACTURAVENTAR INT,IN IDPRODUCTOR INT )
-- REGISTROMERMA(IN IDMERMAR INT, IN CANTIDADUNIDADESR INT, IN JUSTIFICACIONR TEXT(200), IN VALORPERDIDAR REAL,IN FECHAR DATE,IN IDPRODUCTOR INT)
-- REGISTROTIPOGASTO(IN IDTIPOGASTOR INT, IN NOMBRER VARCHAR(60), IN DESCRIPCIONR TEXT(200))
-- REGISTROGASTO(IN IDGASTOR INT, IN FECHAR DATE, IN MONTOR REAL,IN IDTIPOGASTOR INT,IN DPIEMPLEADOR INT)

-- REPORTEMEJORESVENDEDORES;
-- REPORTEVENTASPORDIA;
-- REPORTEMEJORESCLIENTES;
-- REPORTEESTADO;

-- COMPROBARLOGIN(NICK VARCHAR(50),PASS VARCHAR(20)) RETURNS VARCHAR(100)
-- EXISTEUSUARIO(NICK VARCHAR(50)) RETURNS INT
-- EXISTECLIENTE(NITR VARCHAR(20)) RETURNS INT
-- EXISTEPROVEEDOR(NITPROVEEDORR VARCHAR(20)) RETURNS INT
-- EXISTEEMPLEADO(DPIR BIGINT) RETURNS INT
-- EXISTEPRODUCTO(IDPRODUCTOR INT) RETURNS INT
-- EXISTECOMPRA(IDFACTURAR INT) RETURNS INT
-- EXISTEDETALLECOMPRA(IDDETALLECOMPRAR INT,IDFACTURACOMPRAR INT) RETURNS INT
-- EXISTEVENTA(IDFACTURAR INT) RETURNS INT
-- EXISTEDETALLEVENTA(IDDETALLEVENTAR INT,IDFACTURAVENTAR INT) RETURNS INT
-- EXISTEMERMA(IDMERMAR INT) RETURNS INT
-- EXISTETIPOGASTO(IDTIPOGASTOR INT) RETURNS INT
-- EXISTEGASTO(IDGASTOR INT) RETURNS INT
